baseURL = "https://www.danielgong.com/"
languageCode = "en-us"
title = "Daniel Gong"
theme = "minimal"
googleAnalytics = "UA-161446820-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "Daniel Gong"
    description = "Software Developer in Vancouver, BC"
    githubUsername = "#"
    css = ["css/custom.css"]
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "atom-one-dark"
    highlightLanguages = ["go", "c", "java", "javascript", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/Resume.pdf/"
    name = "Resume"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:daniel.gong@alumni.ubc.ca"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/aolingo"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/daniel-gong/"
    name = "linkedin"
    weight = 3

