[build]
publish = "public"
command = "npm run build"

[build.environment]
HUGO_VERSION = "0.67.1"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build -- --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
